### ISSUE TITLE
怎么设置后台ssr开机自启

### ISSUE THREAD

**Issue by ilinsen** [ssrpanel/SSRPanel#303]
还有可以使用cd命令打开shadowsocksr，但是用ftp查看系统文件在根目录没有找到shadowsocksr

**Comment by cciecm** [comment]
我用Ubuntu，这是我的方案：操作系统启动后自动执行logrun.sh
编辑/etc/rc.local，在exit 0之前加入需要运行的脚本logrun.sh
vi /etc/rc.local

#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

bash /root/shadowsocksr/logrun.sh

exit 0

另外一种方案是把SSR绑定为服务，不过我没试那个。
